name: Deploy website to clouflare pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Zola Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: zola-deploy-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            zola-deploy-${{ runner.os }}-
      - name: Build website using zola
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true
          CHECK_LINKS: true
      - name: Deploy to CF Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=mywebsite
