name: Build and Deploy to all web hosting providers

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ["canonical", "www"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build using zola for ${{ matrix.variant }}
        uses: docker://ghcr.io/sirmonteiro/zola-action:v0.20.0
        with:
          base_url: ${{ matrix.variant == 'www' && 'https://www.gabrielsouza.top' || '' }}
          output_dir: public-${{ matrix.variant }}

      - name: Deploy canonical page to CF Pages
        if: matrix.variant == 'canonical'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public-canonical --project-name=mywebsite

      - name: Setup Github Pages
        if: matrix.variant == 'www'
        uses: actions/configure-pages@v5
      - name: Upload artifact to Github Pages
        if: matrix.variant == 'www'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public-www"

      - name: Deploy to Netlify
        if: matrix.variant == 'www'
        uses: South-Paw/action-netlify-cli@v2
        id: netlify
        with:
          args: deploy --json --prod --no-build --dir './public-www' --message 'production [${{ github.sha }}]'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Vercel
        if: matrix.variant == 'www'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: "--prod --no-wait"
          vercel-project-name: gabrielsouzatop
          vercel-version: 41.7.8
          working-directory: ./public-www
          github-comment: false

      - name: Deploy to Firebase
        if: matrix.variant == 'www'
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only hosting -p ./public-www
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-to-github-pages:
    environment:
      name: github-pages
      url: https://www.gabrielsouza.top
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
